# Generated by Django 2.0.5 on 2020-01-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dreamreal',
            table=None,
        ),
    ]
