# Generated by Django 2.0.5 on 2020-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=50)),
                ('Capital', models.CharField(max_length=50)),
                ('Currency', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
            ],
        ),
    ]
