# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuBar.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 120, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 473, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuEdit)
        self.menuView.setObjectName("menuView")
        self.menuFull_View = QtWidgets.QMenu(self.menuView)
        self.menuFull_View.setObjectName("menuFull_View")
        self.menuWindows_2 = QtWidgets.QMenu(self.menuFull_View)
        self.menuWindows_2.setObjectName("menuWindows_2")
        self.menuLinux_2 = QtWidgets.QMenu(self.menuFull_View)
        self.menuLinux_2.setObjectName("menuLinux_2")
        self.menuUbuntu_2 = QtWidgets.QMenu(self.menuFull_View)
        self.menuUbuntu_2.setObjectName("menuUbuntu_2")
        self.menuSmall_View = QtWidgets.QMenu(self.menuView)
        self.menuSmall_View.setObjectName("menuSmall_View")
        self.menuAndroid = QtWidgets.QMenu(self.menuSmall_View)
        self.menuAndroid.setObjectName("menuAndroid")
        self.menuWindows = QtWidgets.QMenu(self.menuSmall_View)
        self.menuWindows.setObjectName("menuWindows")
        self.menuLinux = QtWidgets.QMenu(self.menuSmall_View)
        self.menuLinux.setObjectName("menuLinux")
        self.menuUbuntu = QtWidgets.QMenu(self.menuSmall_View)
        self.menuUbuntu.setObjectName("menuUbuntu")
        self.menuCentOS = QtWidgets.QMenu(self.menuSmall_View)
        self.menuCentOS.setObjectName("menuCentOS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionPreview = QtWidgets.QAction(MainWindow)
        self.actionPreview.setObjectName("actionPreview")
        self.actionEditBy = QtWidgets.QAction(MainWindow)
        self.actionEditBy.setObjectName("actionEditBy")
        self.actionMac = QtWidgets.QAction(MainWindow)
        self.actionMac.setObjectName("actionMac")
        self.actionMac_2 = QtWidgets.QAction(MainWindow)
        self.actionMac_2.setObjectName("actionMac_2")
        self.actionFedora = QtWidgets.QAction(MainWindow)
        self.actionFedora.setObjectName("actionFedora")
        self.actionMint = QtWidgets.QAction(MainWindow)
        self.actionMint.setObjectName("actionMint")
        self.actionAndroid1 = QtWidgets.QAction(MainWindow)
        self.actionAndroid1.setObjectName("actionAndroid1")
        self.actionAndroid2 = QtWidgets.QAction(MainWindow)
        self.actionAndroid2.setObjectName("actionAndroid2")
        self.actionAndroid3 = QtWidgets.QAction(MainWindow)
        self.actionAndroid3.setObjectName("actionAndroid3")
        self.actionAndroid4 = QtWidgets.QAction(MainWindow)
        self.actionAndroid4.setObjectName("actionAndroid4")
        self.actionAndroid5 = QtWidgets.QAction(MainWindow)
        self.actionAndroid5.setObjectName("actionAndroid5")
        self.actionAndroid6 = QtWidgets.QAction(MainWindow)
        self.actionAndroid6.setObjectName("actionAndroid6")
        self.actionAndroid7 = QtWidgets.QAction(MainWindow)
        self.actionAndroid7.setObjectName("actionAndroid7")
        self.actionAndroid8 = QtWidgets.QAction(MainWindow)
        self.actionAndroid8.setObjectName("actionAndroid8")
        self.actionAndroid9 = QtWidgets.QAction(MainWindow)
        self.actionAndroid9.setObjectName("actionAndroid9")
        self.actionAndroid10 = QtWidgets.QAction(MainWindow)
        self.actionAndroid10.setObjectName("actionAndroid10")
        self.actionWindows8 = QtWidgets.QAction(MainWindow)
        self.actionWindows8.setObjectName("actionWindows8")
        self.actionWindows10 = QtWidgets.QAction(MainWindow)
        self.actionWindows10.setObjectName("actionWindows10")
        self.actionRedHat7 = QtWidgets.QAction(MainWindow)
        self.actionRedHat7.setObjectName("actionRedHat7")
        self.actionUbuntu_14_02 = QtWidgets.QAction(MainWindow)
        self.actionUbuntu_14_02.setObjectName("actionUbuntu_14_02")
        self.actionUbuntu_16_02 = QtWidgets.QAction(MainWindow)
        self.actionUbuntu_16_02.setObjectName("actionUbuntu_16_02")
        self.actionUbuntu_18_02 = QtWidgets.QAction(MainWindow)
        self.actionUbuntu_18_02.setObjectName("actionUbuntu_18_02")
        self.actionUbunut_20_02 = QtWidgets.QAction(MainWindow)
        self.actionUbunut_20_02.setObjectName("actionUbunut_20_02")
        self.actionCentOS6 = QtWidgets.QAction(MainWindow)
        self.actionCentOS6.setObjectName("actionCentOS6")
        self.actionCentOS7 = QtWidgets.QAction(MainWindow)
        self.actionCentOS7.setObjectName("actionCentOS7")
        self.actionWindows8_2 = QtWidgets.QAction(MainWindow)
        self.actionWindows8_2.setObjectName("actionWindows8_2")
        self.actionRedHat = QtWidgets.QAction(MainWindow)
        self.actionRedHat.setObjectName("actionRedHat")
        self.action14_02 = QtWidgets.QAction(MainWindow)
        self.action14_02.setObjectName("action14_02")
        self.action18_02 = QtWidgets.QAction(MainWindow)
        self.action18_02.setObjectName("action18_02")
        self.action20_2 = QtWidgets.QAction(MainWindow)
        self.action20_2.setObjectName("action20_2")
        self.actioncopy = QtWidgets.QAction(MainWindow)
        self.actioncopy.setObjectName("actioncopy")
        self.actionpast = QtWidgets.QAction(MainWindow)
        self.actionpast.setObjectName("actionpast")
        self.menuFile.addAction(self.actionEdit)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionopen)
        self.menuFile.addAction(self.actioncopy)
        self.menuFile.addAction(self.actionpast)
        self.menuWindows_2.addAction(self.actionWindows8_2)
        self.menuLinux_2.addAction(self.actionRedHat)
        self.menuUbuntu_2.addAction(self.action14_02)
        self.menuUbuntu_2.addAction(self.action18_02)
        self.menuUbuntu_2.addAction(self.action20_2)
        self.menuFull_View.addAction(self.menuWindows_2.menuAction())
        self.menuFull_View.addAction(self.menuLinux_2.menuAction())
        self.menuFull_View.addAction(self.actionMac)
        self.menuFull_View.addAction(self.menuUbuntu_2.menuAction())
        self.menuAndroid.addAction(self.actionAndroid1)
        self.menuAndroid.addAction(self.actionAndroid2)
        self.menuAndroid.addAction(self.actionAndroid3)
        self.menuAndroid.addAction(self.actionAndroid4)
        self.menuAndroid.addAction(self.actionAndroid5)
        self.menuAndroid.addAction(self.actionAndroid6)
        self.menuAndroid.addAction(self.actionAndroid7)
        self.menuAndroid.addAction(self.actionAndroid8)
        self.menuAndroid.addAction(self.actionAndroid9)
        self.menuAndroid.addAction(self.actionAndroid10)
        self.menuWindows.addAction(self.actionWindows8)
        self.menuWindows.addAction(self.actionWindows10)
        self.menuLinux.addAction(self.actionRedHat7)
        self.menuUbuntu.addAction(self.actionUbuntu_14_02)
        self.menuUbuntu.addAction(self.actionUbuntu_16_02)
        self.menuUbuntu.addAction(self.actionUbuntu_18_02)
        self.menuUbuntu.addAction(self.actionUbunut_20_02)
        self.menuCentOS.addAction(self.actionCentOS6)
        self.menuCentOS.addAction(self.actionCentOS7)
        self.menuSmall_View.addAction(self.menuWindows.menuAction())
        self.menuSmall_View.addAction(self.menuLinux.menuAction())
        self.menuSmall_View.addAction(self.actionMac_2)
        self.menuSmall_View.addAction(self.menuUbuntu.menuAction())
        self.menuSmall_View.addAction(self.menuCentOS.menuAction())
        self.menuSmall_View.addAction(self.actionFedora)
        self.menuSmall_View.addAction(self.actionMint)
        self.menuSmall_View.addAction(self.menuAndroid.menuAction())
        self.menuView.addAction(self.menuFull_View.menuAction())
        self.menuView.addAction(self.menuSmall_View.menuAction())
        self.menuEdit.addAction(self.menuView.menuAction())
        self.menuEdit.addAction(self.actionPreview)
        self.menuEdit.addAction(self.actionEditBy)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionSave.triggered.connect(lambda: self.clicked("Saved Option Selected"))
        self.actionSave_as.triggered.connect(lambda: self.clicked("Selected Save as option"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ravi Prasad"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuFull_View.setTitle(_translate("MainWindow", "Full View"))
        self.menuWindows_2.setTitle(_translate("MainWindow", "Windows"))
        self.menuLinux_2.setTitle(_translate("MainWindow", "Linux"))
        self.menuUbuntu_2.setTitle(_translate("MainWindow", "Ubuntu"))
        self.menuSmall_View.setTitle(_translate("MainWindow", "Small View"))
        self.menuAndroid.setTitle(_translate("MainWindow", "Android"))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows"))
        self.menuLinux.setTitle(_translate("MainWindow", "Linux"))
        self.menuUbuntu.setTitle(_translate("MainWindow", "Ubuntu"))
        self.menuCentOS.setTitle(_translate("MainWindow", "CentOS"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionPreview.setText(_translate("MainWindow", "Preview"))
        self.actionEditBy.setText(_translate("MainWindow", "EditBy"))
        self.actionMac.setText(_translate("MainWindow", "Mac"))
        self.actionMac_2.setText(_translate("MainWindow", "Mac"))
        self.actionFedora.setText(_translate("MainWindow", "Fedora"))
        self.actionMint.setText(_translate("MainWindow", "Mint"))
        self.actionAndroid1.setText(_translate("MainWindow", "Android1"))
        self.actionAndroid2.setText(_translate("MainWindow", "Android2"))
        self.actionAndroid3.setText(_translate("MainWindow", "Android3"))
        self.actionAndroid4.setText(_translate("MainWindow", "Android4"))
        self.actionAndroid5.setText(_translate("MainWindow", "Android5"))
        self.actionAndroid6.setText(_translate("MainWindow", "Android6"))
        self.actionAndroid7.setText(_translate("MainWindow", "Android7"))
        self.actionAndroid8.setText(_translate("MainWindow", "Android8"))
        self.actionAndroid9.setText(_translate("MainWindow", "Android9"))
        self.actionAndroid10.setText(_translate("MainWindow", "Android10"))
        self.actionWindows8.setText(_translate("MainWindow", "Windows8"))
        self.actionWindows10.setText(_translate("MainWindow", "Windows10"))
        self.actionRedHat7.setText(_translate("MainWindow", "RedHat7"))
        self.actionUbuntu_14_02.setText(_translate("MainWindow", "Ubuntu 14.02"))
        self.actionUbuntu_16_02.setText(_translate("MainWindow", "Ubuntu 16.02"))
        self.actionUbuntu_18_02.setText(_translate("MainWindow", "Ubuntu 18.02"))
        self.actionUbunut_20_02.setText(_translate("MainWindow", "Ubunut 20.02"))
        self.actionCentOS6.setText(_translate("MainWindow", "CentOS6"))
        self.actionCentOS7.setText(_translate("MainWindow", "CentOS7"))
        self.actionWindows8_2.setText(_translate("MainWindow", "Windows8"))
        self.actionRedHat.setText(_translate("MainWindow", "RedHat"))
        self.action14_02.setText(_translate("MainWindow", "14.02"))
        self.action18_02.setText(_translate("MainWindow", "18.02"))
        self.action20_2.setText(_translate("MainWindow", "20.2"))
        self.actioncopy.setText(_translate("MainWindow", "copy"))
        self.actioncopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionpast.setText(_translate("MainWindow", "past"))
        self.actionpast.setShortcut(_translate("MainWindow", "Ctrl+P"))

    def clicked(self, text):
        self.label.setText(text)
        self.label.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
