from email.message import EmailMessage
import smtplib

EMAIL = "mouni.14338@gmail.com"
PASSWORD = "Prasadravi@24"


msg= EmailMessage()

msg['Subject'] = 'Email Using Python'
msg['From'] = EMAIL
msg['To'] = ['mouni.14338@gmail.com']

message = "This email is generated by python"
msg.set_content(message)

attachments = ['Hacking.py']

for path in attachments:
    with open(path, 'rb') as file:
        data = file.read()
        name = path.split("\\")[-1]

        msg.add_attachment(data, maintype='application',
                           subtype = 'octet-strem',
                           filename = name)

with smtplib.SMTP_SSL('smtp.gmail.com',465) as smtp:
    smtp.login(EMAIL, PASSWORD)
    smtp.send_message(msg)